# Generated by Django 4.0 on 2022-02-10 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('Email', models.EmailField(max_length=50, verbose_name='Email')),
                ('address_line', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(default=models.CharField(max_length=255, verbose_name='Address Line 1'), max_length=255, null=True, verbose_name='Address Line 2')),
                ('postcode', models.CharField(max_length=50, verbose_name='Postcode')),
                ('town_city', models.CharField(max_length=150, verbose_name='Town/City/State')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Customer')),
            ],
        ),
    ]
