# Generated by Django 4.0 on 2022-02-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Address Line 2'),
        ),
    ]
