# Generated by Django 4.0.5 on 2022-06-16 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.TextField(max_length=100)),
                ('t_cr_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('t_due_date', models.DateTimeField(blank=True)),
                ('t_completed', models.IntegerField(default=0)),
            ],
        ),
    ]
