info:
  _collection_link: https://restless-meadow-436438.postman.co/workspace/New-Team-Workspace~517136db-95ac-461a-b44d-35d1761371b6/collection/23122223-732594a0-4bd8-4760-b445-3e3a3c2b8264?action=share&source=collection_link&creator=23122223
  _exporter_id: '23122223'
  _postman_id: 732594a0-4bd8-4760-b445-3e3a3c2b8264
  name: api_collection
  schema: https://schema.getpostman.com/json/collection/v2.1.0/collection.json
item:
- name: login
  request:
    body:
      mode: raw
      options:
        raw:
          language: json
      raw: "{\r\n    \"username\": \"admin\",\r\n    \"password\": \"admin\"\r\n}"
    header: []
    method: POST
    url:
      host:
      - localhost
      path:
      - login
      - ''
      port: '8000'
      protocol: http
      raw: http://localhost:8000/login/
  response: []
- name: add_customer
  request:
    body:
      mode: raw
      options:
        raw:
          language: json
      raw: "{\r\n    \"first_name\": \"valli\",\r\n    \"last_name\": \"hussain\"\
        ,\r\n    \"email\": \"valli@gmail.com\",\r\n    \"dob\": \"2024/1/10\",\r\n\
        \    \"phone\": \"123456789\"\r\n}"
    header: []
    method: POST
    url:
      host:
      - localhost
      path:
      - add
      - customer
      - ''
      port: '8000'
      protocol: http
      raw: http://localhost:8000/add/customer/
  response: []
- name: logout
  request:
    body:
      mode: raw
      options:
        raw:
          language: json
      raw: ''
    header: []
    method: POST
    url:
      host:
      - localhost
      path:
      - logout
      - ''
      port: '8000'
      protocol: http
      raw: http://localhost:8000/logout/
  response: []
