# Generated by Django 3.2.18 on 2023-04-16 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=52)),
                ('continent', models.CharField(choices=[('South America', 'south america'), ('Asia', 'asia'), ('Antarctica', 'antarctica'), ('Europe', 'europe'), ('Oceania', 'oceania'), ('North America', 'north america'), ('Africa', 'africa')], default='Asia', max_length=20)),
                ('Region', models.CharField(default='', max_length=26)),
                ('surfacearea', models.FloatField(default='0.00')),
                ('indepyear', models.IntegerField(null=True)),
                ('population', models.IntegerField(default='0')),
                ('lifeexpectancy', models.FloatField(null=True)),
                ('GNP', models.FloatField(null=True)),
                ('GNPOld', models.FloatField(null=True)),
                ('localname', models.CharField(default='', max_length=45)),
                ('governmentform', models.CharField(default='', max_length=45)),
                ('headofstate', models.CharField(default=None, max_length=60, null=True)),
                ('capital', models.IntegerField(default=None, null=True)),
                ('code2', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='countrylanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='', max_length=30)),
                ('isofficial', models.BooleanField(default='F')),
                ('percentage', models.FloatField(default='0.0')),
                ('countrycode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.country')),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=35)),
                ('district', models.CharField(default='', max_length=20)),
                ('population', models.IntegerField(default=0)),
                ('countrycode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.country')),
            ],
        ),
    ]
