# Generated by Django 3.2.18 on 2023-04-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('Africa', 'africa'), ('Europe', 'europe'), ('North America', 'north america'), ('Oceania', 'oceania'), ('South America', 'south america'), ('Antarctica', 'antarctica'), ('Asia', 'asia')], default='Asia', max_length=20),
        ),
    ]
