# Generated by Django 3.2.18 on 2023-04-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_country_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('Asia', 'asia'), ('Africa', 'africa'), ('North America', 'north america'), ('Europe', 'europe'), ('Oceania', 'oceania'), ('Antarctica', 'antarctica'), ('South America', 'south america')], default='Asia', max_length=20),
        ),
    ]
