# Generated by Django 3.2.18 on 2023-04-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_country_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('South America', 'south america'), ('Antarctica', 'antarctica'), ('Africa', 'africa'), ('Europe', 'europe'), ('Oceania', 'oceania'), ('Asia', 'asia'), ('North America', 'north america')], default='Asia', max_length=20),
        ),
    ]
