version: "25.0.3"

services:
  web_backend:
    build: 
        context: ./Django
        dockerfile: Dockerfile
    image: web_backend:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  web_frontend:
    build: 
        context: ./reactjs
        dockerfile: Dockerfile
    image: web_frontend:latest
    ports:
      - 3000:3000
    