version: "25.0.3"

services:
  django:
      image: myimage
      container_name: mycontainer
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - 8000:8000
        - 8001:8001